[workspace]
resolver = "2"
members = [
    "proto-build",
    "side-proto",
]

[workspace.dependencies]
cosmrs = "0.22"
tendermint-proto = "0.40.0"
cosmos-sdk-proto = "0.27.0"
prost = "0.13"
prost-types = "0.13"

